language: php

php:
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - mkdir -p build/proxy
  - phpunit

after_success:
- travis_retry php vendor/bin/coveralls -v